In [19]:
list_1dim = [1,2,3,4,5]
list_1dim[0]

1

In [20]:
list_2dim = [[1,2,3],
            [4,5,6],
            [7,8,9]]
list_2dim[0][1]

2

In [18]:
# 3 dimensionsal

2

In [3]:
import numpy as np

In [14]:
np_array = np.array([1,2,3,4,5], dtype=int)
print(np_array)

In [23]:
print(np_array[0])
for i in np_array:
    print(i)

1
1
2
3
4
5


In [30]:
def access_element(array, index):
    if index >= len(array):
        print('index is out of range')
    else:
        print(array[index])

In [31]:
access_element(np_array, 100)

index is out of range


In [32]:
# linear search
np_array = np.array([1,2,3,4,5,6], dtype = int)

In [44]:
# Linear Search
def linear_search(array, target):
    for i in range(len(array)):
        if array[i] == target:
            return print(f" target: {target}, index: {i}")
    return print("target not in index")

In [45]:
linear_search(np_array, 5)
# time compleity: O(n)

 target: 5, index: 4


In [97]:
# 2 dimensional array
np_array = np.array([[1,5,24,44,56],
                    [5,4,3,10,11],
                    [6,7,8,9,10]], dtype = int)

In [98]:
np_array

array([[ 1,  5, 24, 44, 56],
       [ 5,  4,  3, 10, 11],
       [ 6,  7,  8,  9, 10]])

In [99]:
np_array.sort()
np_array[0][4]

56

In [100]:
# 2 dimensional array insertion

In [101]:
# adding column
new_np_array = np.insert(np_array,0,[[1,2,3]], axis = 1)

In [102]:
new_np_array

array([[ 1,  1,  5, 24, 44, 56],
       [ 2,  3,  4,  5, 10, 11],
       [ 3,  6,  7,  8,  9, 10]])

In [103]:
new2_np_array = np.insert(new_np_array,1,[[1,2,3,4,5,6]], axis = 0)

In [104]:
print(new_np_array)

[[ 1  1  5 24 44 56]
 [ 2  3  4  5 10 11]
 [ 3  6  7  8  9 10]]


In [105]:
# accessing an element
def access_index(array, row_index, column_index):
    if column_index >= len(array[0]) or row_index >= len(array):
        print('out of index')
    else:
        return array[row_index][column_index]

In [106]:
np_array.sort()

In [120]:
# transverse/loop through 2 dimensional array
def traverse_array(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

In [122]:
traverse_array(np_array)
# time complexity: O(n2)

1
5
24
44
56
3
4
5
10
11
6
7
8
9
10


In [127]:
# searching two dimensional array (linear search)
def linear_search(array, target):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == target:
                print(array)
                return i,j,target
    return -1

In [128]:
linear_search(np_array, 10)

# time complexity: O(mn)

[[ 1  5 24 44 56]
 [ 3  4  5 10 11]
 [ 6  7  8  9 10]]


(1, 3, 10)